name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Run tests
        run: python -m pytest -v tests
